\LoadClass[UTF8]{ctexart}
\NeedsTeXFormat{LaTeX2e}

\RequirePackage{amsmath}
\RequirePackage{amssymb}

\author{皇甫硕龙}

\newcommand{\N}{\mathbb N}
\newcommand{\R}{\mathbb R}
\newcommand{\Z}{\mathbb Z}
\newcommand{\C}{\mathbb C}
\newcommand{\Q}{\mathbb Q}
\newcommand{\dd}{\mathrm d}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}
\newcommand{\eqnref}[1]{(\ref{#1})}

% 概率
\newcommand{\prob}[1]{P\left(#1\right)}
\newcommand{\cprob}[2]{P\left(#1|#2\right)}

% 期望
\newcommand{\expt}[1]{E\left(#1\right)}
\newcommand{\cexpt}[2]{E\left(#1|#2\right)}

\newcommand{\bs}{\boldsymbol}